# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gsample_wor <- function(size, weights, log_weights) {
    .Call(`_gsample_gsample_wor`, size, weights, log_weights)
}

gsample_wr <- function(size, weights, log_weights) {
    .Call(`_gsample_gsample_wr`, size, weights, log_weights)
}

