# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gsample_wor <- function(n, size, weights, log_weights) {
    .Call(`_gsample_gsample_wor`, n, size, weights, log_weights)
}

