# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gsample_introselect <- function(n, size, prob) {
    .Call(`_gsample_gsample_introselect`, n, size, prob)
}

gsample_partial_heap <- function(n, size, prob) {
    .Call(`_gsample_gsample_partial_heap`, n, size, prob)
}

